### ISSUE TITLE
Improve support for 1.21.3 version

### ISSUE THREAD

**Issue by NoltoxGit** [MC-Machinations/TreasureMapsPlus#7]
### Expected behavior

The aim is to have no errors when the plugin starts up in 1.21.3.

### Observed/Actual behavior

When I start my server with the latest Paper 1.21.3 version, i've error in my console
```log
[11:04:45 ERROR]: Could not pass event ServerLoadEvent to TreasureMapsPlus v0.7.1
java.lang.NoSuchMethodError: 'net.minecraft.core.Registry net.minecraft.core.RegistryAccess.registryOrThrow(net.minecraft.resources.ResourceKey)'
at TreasureMapsPlus-0.7.1.jar/me.machinemaker.treasuremapsplus.RegistryOverride.override(RegistryOverride.java:57) ~[TreasureMapsPlus-0.7.1.jar:?]
at TreasureMapsPlus-0.7.1.jar/me.machinemaker.treasuremapsplus.loot.ExplorationMapItemFunctionOverride.override(ExplorationMapItemFunctionOverride.java:88) ~[TreasureMapsPlus-0.7.1.jar:?]
at TreasureMapsPlus-0.7.1.jar/me.machinemaker.treasuremapsplus.listener.ServerLoad.onEvent(ServerLoad.java:44) ~[TreasureMapsPlus-0.7.1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:774) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-29-be886cf]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps/models to reproduce

1. Use the latest Paper version,
2. Use the latest TreasureMapsPlus version,
3. See the console.

### Plugin and Datapack List

Server Plugins (85):
Paper Plugins:
- HuskHomes, RoseStacker, TreasureMapsPlus
Bukkit Plugins:
- AdvancedChests, ajLeaderboards, AxBoosters, AxGraves, AxInventoryRestore, AxVaults, BattlePass, BeautyQuests, BeautyQuests-Expansion, BlockTracker, BottledExp, ChatGames-Premium, ChestProtect, Chunky, ChunkyBorder, ClueScrolls, CMI, CMIEInjector, CMILib, ContainerPassthrough, CoreProtect, craftableinvframes, CrazyEnvoys, CustomFishing, CustomNameplates, DeluxeMenus, DualHorse, eco, EcoEnchants, EcoItems, EconomyBridge, EternalTags, ExcellentCrates, ExcellentShop, F3NPerm, FastAsyncWorldEdit, GSit, HeadDatabase, HubParkour, InteractionVisualizer, ItemEdit, ItemsAdder, Jobs, Lands, libreforge, LoneLibs, LuckPerms, MasterCooldowns, Mclogs, MobFarmManager, ModelEngine, Multiverse-Core, MythicMobs, NBTAPI, nightcore, OpenInv, packetevents, PinataParty, Pl-Hide-Pro, PlaceholderAPI, PlayerPoints, PlayerWarps, PluginManager, PremiumVanish, ProtectedDebugStick, ProtocolLib, PurpurExtras, Quests, RoseChat, RoseLoot, ServerVariables, spark, TAB, TradeMe, Tweakin, UpgradeableHoppers, UpgradeableSpawners, Vault, VoteParty, WorldGuard, XenoWorldReset, ZNPCsPlus

### Server Version Info

This server is running Paper version 1.21.3-29-master@be886cf (2024-11-15T09:07:14Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

### Plugin Version

Command doesn't exist??

**Comment by Machine-Maker** [comment]
Can you test out [TreasureMapsPlus.zip](https://nightly.link/MC-Machinations/TreasureMapsPlus/actions/runs/11880897133/TreasureMapsPlus.zip)? If it fixes your issues, I'll release it in a bit.

**Comment by NoltoxGit** [comment]
> Can you test out [TreasureMapsPlus.zip](https://nightly.link/MC-Machinations/TreasureMapsPlus/actions/runs/11880897133/TreasureMapsPlus.zip)? If it fixes your issues, I'll release it in a bit.

Hi!
The link doesn't work :(

**Comment by Machine-Maker** [comment]
Sorry, try again. I hadn't authorized downloads on this repo for some reason.

**Comment by NoltoxGit** [comment]
> Sorry, try again. I hadn't authorized downloads on this repo for some reason.

Ty, i'll try this now!

**Comment by NoltoxGit** [comment]
> Sorry, try again. I hadn't authorized downloads on this repo for some reason.

I don't think it's working...
I've just regenerated my world in version 1.21.3 and nothing works :(

Video:
https://cdn.discordapp.com/attachments/1130933626951975094/1307821829683023974/2024-11-17_22-34-55.mp4?ex=673bb37e&is=673a61fe&hm=7bbb482887f54dd1e167e765573ec8de1016416c1c5e3a448df6f5cef1b33230&

**Comment by NoltoxGit** [comment]
Hey @Machine-Maker,
Do you have any news about this bug?

**Comment by NoltoxGit** [comment]
Hey @Machine-Maker,
Do you have any news about this bug?

**Comment by Machine-Maker** [comment]
I just updated it to 1.21.4 and it works fine, both buried treasure maps as well as the 2 supported villager map trades. (the video is now expired I think, I never got to view it). Try with the [updated version](https://hangar.papermc.io/Machine_Maker/TreasureMapsPlus/versions/0.7.2) on 1.21.4 and if you still can't get it to work, we can reopen this.
